/**
 * This code was GENERATED using the solita package.
 * Please DO NOT EDIT THIS FILE, instead rerun solita to update it or write a wrapper to add functionality.
 *
 * See: https://github.com/metaplex-foundation/solita
 */

import * as beet from '@metaplex-foundation/beet';
import * as web3 from '@solana/web3.js';

/**
 * @category Instructions
 * @category CleanupWrapper
 * @category generated
 */
export const CleanupWrapperStruct = new beet.BeetArgsStruct<{
  instructionDiscriminator: number;
}>([['instructionDiscriminator', beet.u8]], 'CleanupWrapperInstructionArgs');
/**
 * Accounts required by the _CleanupWrapper_ instruction
 *
 * @property [_writable_] payer
 * @property [_writable_] wrapper
 * @category Instructions
 * @category CleanupWrapper
 * @category generated
 */
export type CleanupWrapperInstructionAccounts = {
  payer: web3.PublicKey;
  wrapper: web3.PublicKey;
  systemProgram?: web3.PublicKey;
};

export const cleanupWrapperInstructionDiscriminator = 5;

/**
 * Creates a _CleanupWrapper_ instruction.
 *
 * @param accounts that will be accessed while the instruction is processed
 * @category Instructions
 * @category CleanupWrapper
 * @category generated
 */
export function createCleanupWrapperInstruction(
  accounts: CleanupWrapperInstructionAccounts,
  programId = new web3.PublicKey('wMNFSTkir3HgyZTsB7uqu3i7FA73grFCptPXgrZjksL'),
) {
  const [data] = CleanupWrapperStruct.serialize({
    instructionDiscriminator: cleanupWrapperInstructionDiscriminator,
  });
  const keys: web3.AccountMeta[] = [
    {
      pubkey: accounts.payer,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.wrapper,
      isWritable: true,
      isSigner: false,
    },
    {
      pubkey: accounts.systemProgram ?? web3.SystemProgram.programId,
      isWritable: false,
      isSigner: false,
    },
  ];

  const ix = new web3.TransactionInstruction({
    programId,
    keys,
    data,
  });
  return ix;
}
